try:
    import RPi.GPIO as GPIO
    GPIO_ENABLED = True
except:
    import Mock.GPIO as GPIO
    GPIO_ENABLED = False

import pygame
from pygame.color import Color

REFRESH_RATE = 30 # frames per second

# PINS
LIGHT_PIN = 12 # allows hardware PWM
BUTTON_PIN = 37
STEPPER1_PINS = (8, 10, 16, 18, 15)
STEPPER2_PINS = (22, 24, 26, 35, 13)
STEPPER3_PINS = (3, 5, 7, 11, 29)
# STEPPER4_PINS = (32, 36, 38, 40)

# EVENTS
ENABLE_BUTTON_EVENT = pygame.USEREVENT + 1
VEND_CANDY_EVENT = pygame.USEREVENT + 2
MUSIC_END_EVENT = pygame.USEREVENT + 3
BUTTON_PRESSED_EVENT = pygame.USEREVENT + 4
INTERNAL_BUTTON_PRESSED_EVENT = pygame.USEREVENT + 5
IDLE_TIME_HIT_EVENT = pygame.USEREVENT + 6
INTERNAL_IDLE_SOUND_END_EVENT = pygame.USEREVENT + 7
INTERNAL_MUSIC_FADE_UP_EVENT = pygame.USEREVENT + 8
INTERNAL_MUSIC_FADE_DOWN_EVENT = pygame.USEREVENT + 9
READY_FOR_NEXT_PLAYER_EVENT = pygame.USEREVENT + 10
INTERNAL_READY_FOR_NEXT_PLAYER_SOUND_DONE_EVENT = pygame.USEREVENT + 11
INTERNAL_LIGHT_BLINK_EVENT = pygame.USEREVENT + 12

# COLORS
COLOR_PRIMARY = Color('#F05D23')
COLOR_SECONDARY = Color('#C5D86D')
COLOR_GOOD = Color('#FF7600')
COLOR_BAD = Color('#CD113B')
COLOR_WHITE = Color('#FFFFFF')
COLOR_BLACK = Color('#000000')

# TIMING
IDLE_TIME = 60000 # milliseconds
LIGHT_BLINK_TIME = 400
